-- ==========================================
-- HUGE WORLDWIDE GEOGRAPHY DATABASE (Massively Expanded)
-- ==========================================
local locationDB = {
    [0] = { -- ARCTIC OCEAN
        {sea = "Barents Sea", nearbyCountry = "Norway", region = "Arctic Ocean"},
        {sea = "Kara Sea", nearbyCountry = "Russia", region = "Arctic Ocean"},
        {sea = "Laptev Sea", nearbyCountry = "Russia", region = "Arctic Ocean"},
        {sea = "East Siberian Sea", nearbyCountry = "Russia", region = "Arctic Ocean"},
        {sea = "Chukchi Sea", nearbyCountry = "United States (Alaska)", region = "Arctic Ocean"},
        {sea = "Beaufort Sea", nearbyCountry = "Canada", region = "Arctic Ocean"},
        {sea = "Lincoln Sea", nearbyCountry = "Greenland", region = "Arctic Ocean"},
        {sea = "Wandel Sea", nearbyCountry = "Greenland", region = "Arctic Ocean"},
        {sea = "Greenland Sea", nearbyCountry = "Greenland (Denmark)", region = "Arctic Ocean"},
        {sea = "Norwegian Sea", nearbyCountry = "Norway", region = "Arctic Ocean"},
        {sea = "White Sea", nearbyCountry = "Russia", region = "Arctic Ocean"},
        {sea = "Svalbard Archipelago", nearbyCountry = "Svalbard Islands (Norway)", region = "Arctic Ocean"},
        {sea = "Victoria Island Coast", nearbyCountry = "Northern Canada", region = "Arctic Ocean"},
        {sea = "Deep Arctic Ocean", nearbyCountry = "North Pole Region", region = "Arctic Ocean"},
        {sea = "Baffin Bay", nearbyCountry = "Canada and Greenland", region = "Arctic Ocean"}
    },
    [1] = { -- SOUTHERN OCEAN
        {sea = "Weddell Sea", nearbyCountry = "Antarctica Coast", region = "Southern Ocean"},
        {sea = "Ross Sea", nearbyCountry = "Antarctica Coast", region = "Southern Ocean"},
        {sea = "Drake Passage", nearbyCountry = "Chile and Argentina Coast", region = "Southern Ocean"},
        {sea = "Amundsen Sea", nearbyCountry = "Marie Byrd Land Coast", region = "Southern Ocean"},
        {sea = "Bellingshausen Sea", nearbyCountry = "Antarctica", region = "Southern Ocean"},
        {sea = "Davis Sea", nearbyCountry = "Antarctica", region = "Southern Ocean"},
        {sea = "Mawson Sea", nearbyCountry = "Antarctica", region = "Southern Ocean"},
        {sea = "Elephant Island Waters", nearbyCountry = "Antarctica Region", region = "Southern Ocean"},
        {sea = "Macquarie Island Coast", nearbyCountry = "Macquarie Island (Australia)", region = "Southern Ocean"},
        {sea = "South Georgia Coast", nearbyCountry = "South Georgia Island", region = "Southern Ocean"},
        {sea = "South Sandwich Islands", nearbyCountry = "British Overseas Territory", region = "Southern Ocean"},
        {sea = "South Orkney Islands", nearbyCountry = "Antarctica", region = "Southern Ocean"},
        {sea = "Kerguelen Waters", nearbyCountry = "Kerguelen Islands (France)", region = "Southern Ocean"},
        {sea = "Bouvet Island Coast", nearbyCountry = "Bouvet Island (Norway)", region = "Southern Ocean"}
    },
    [2] = { -- INDIAN OCEAN
        {sea = "Arabian Sea", nearbyCountry = "Pakistan Coast", region = "Indian Ocean"},
        {sea = "Manora Island Coast", nearbyCountry = "Karachi, Pakistan", region = "Indian Ocean"},
        {sea = "Gwadar Bay", nearbyCountry = "Balochistan, Pakistan", region = "Indian Ocean"},
        {sea = "Gulf of Oman", nearbyCountry = "Oman and Iran", region = "Indian Ocean"},
        {sea = "Strait of Hormuz", nearbyCountry = "Oman and Iran", region = "Indian Ocean"},
        {sea = "Persian Gulf", nearbyCountry = "UAE, Saudi Arabia, Qatar, Bahrain", region = "Indian Ocean"},
        {sea = "Gulf of Aden", nearbyCountry = "Yemen and Somalia", region = "Indian Ocean"},
        {sea = "Bab-el-Mandeb Strait", nearbyCountry = "Yemen, Djibouti, Eritrea", region = "Indian Ocean"},
        {sea = "Red Sea Coast", nearbyCountry = "Eritrea and Sudan", region = "Indian Ocean"},
        {sea = "Red Sea", nearbyCountry = "Saudi Arabia and Egypt", region = "Indian Ocean"},
        {sea = "Maldives Atolls", nearbyCountry = "Maldives", region = "Indian Ocean"},
        {sea = "Laccadive Sea", nearbyCountry = "Lakshadweep Islands (India)", region = "Indian Ocean"},
        {sea = "Bay of Bengal", nearbyCountry = "Bangladesh and India", region = "Indian Ocean"},
        {sea = "Andaman Sea", nearbyCountry = "Andaman & Nicobar Islands (India)", region = "Indian Ocean"},
        {sea = "Strait of Malacca", nearbyCountry = "Singapore and Malaysia", region = "Indian Ocean"},
        {sea = "Seychelles Waters", nearbyCountry = "Seychelles Islands", region = "Indian Ocean"},
        {sea = "Mauritius Coast", nearbyCountry = "Mauritius Island", region = "Indian Ocean"},
        {sea = "Madagascar Coast", nearbyCountry = "Madagascar", region = "Indian Ocean"},
        {sea = "Mozambique Channel", nearbyCountry = "Mozambique and Madagascar", region = "Indian Ocean"},
        {sea = "Zanzibar Coast", nearbyCountry = "Zanzibar Island (Tanzania)", region = "Indian Ocean"},
        {sea = "Comoros Archipelago", nearbyCountry = "Comoros", region = "Indian Ocean"},
        {sea = "Chagos Archipelago", nearbyCountry = "British Indian Ocean Territory", region = "Indian Ocean"},
        {sea = "Cocos (Keeling) Islands", nearbyCountry = "Australia Territory", region = "Indian Ocean"},
        {sea = "Christmas Island Coast", nearbyCountry = "Australia Territory", region = "Indian Ocean"}
    },
    [3] = { -- ATLANTIC OCEAN
        {sea = "St. Helena Island Waters", nearbyCountry = "St. Helena (UK Territory)", region = "Atlantic Ocean"},
        {sea = "Ascension Island", nearbyCountry = "UK Overseas Territory", region = "Atlantic Ocean"},
        {sea = "Tristan da Cunha", nearbyCountry = "Remote Atlantic Islands", region = "Atlantic Ocean"},
        {sea = "Gulf of Guinea", nearbyCountry = "Nigeria, Ghana, Equatorial Guinea", region = "Atlantic Ocean"},
        {sea = "Cape Verde Waters", nearbyCountry = "Cape Verde Islands", region = "Atlantic Ocean"},
        {sea = "Canary Islands Coast", nearbyCountry = "Canary Islands (Spain)", region = "Atlantic Ocean"},
        {sea = "Azores Archipelago", nearbyCountry = "Azores Islands (Portugal)", region = "Atlantic Ocean"},
        {sea = "Madeira Islands", nearbyCountry = "Portugal Territory", region = "Atlantic Ocean"},
        {sea = "Sargasso Sea", nearbyCountry = "Open North Atlantic", region = "North Atlantic Ocean"},
        {sea = "Bermuda Triangle", nearbyCountry = "Bermuda Island", region = "North Atlantic Ocean"},
        {sea = "Bahamas Archipelago", nearbyCountry = "The Bahamas", region = "North Atlantic Ocean"},
        {sea = "Caribbean Sea", nearbyCountry = "Jamaica, Cuba, Puerto Rico", region = "Atlantic Ocean"},
        {sea = "Gulf of Mexico", nearbyCountry = "Mexico and USA Coast", region = "Atlantic Ocean"},
        {sea = "Labrador Sea", nearbyCountry = "Canada and Greenland", region = "North Atlantic Ocean"},
        {sea = "Celtic Sea", nearbyCountry = "Ireland and France", region = "North Atlantic Ocean"},
        {sea = "English Channel", nearbyCountry = "United Kingdom and France", region = "Atlantic Ocean"},
        {sea = "North Sea", nearbyCountry = "UK, Norway, Netherlands", region = "North Atlantic Ocean"},
        {sea = "Bay of Biscay", nearbyCountry = "France and Spain", region = "Atlantic Ocean"},
        {sea = "Strait of Gibraltar", nearbyCountry = "Spain and Morocco", region = "Atlantic Ocean"},
        {sea = "Falkland Islands Coast", nearbyCountry = "Falkland Islands", region = "Atlantic Ocean"},
        {sea = "South American Coast", nearbyCountry = "Brazil (Rio de Janeiro)", region = "Atlantic Ocean"},
        {sea = "Argentine Sea", nearbyCountry = "Argentina Coast", region = "Atlantic Ocean"}
    },
    [4] = { -- PACIFIC OCEAN
        {sea = "Point Nemo (Oceanic Pole of Inaccessibility)", nearbyCountry = "Deepest South Pacific Ocean", region = "Pacific Ocean"},
        {sea = "Gulf of Thailand", nearbyCountry = "Thailand, Cambodia, Vietnam", region = "Pacific Ocean"},
        {sea = "Sea of Japan", nearbyCountry = "Japan and South Korea", region = "Pacific Ocean"},
        {sea = "East China Sea", nearbyCountry = "China and Japan", region = "Pacific Ocean"},
        {sea = "Yellow Sea", nearbyCountry = "China and North Korea", region = "Pacific Ocean"},
        {sea = "South China Sea", nearbyCountry = "Philippines, Vietnam, Malaysia", region = "Pacific Ocean"},
        {sea = "Philippine Sea", nearbyCountry = "Philippines", region = "Pacific Ocean"},
        {sea = "Celebes Sea", nearbyCountry = "Indonesia and Philippines", region = "Pacific Ocean"},
        {sea = "Java Sea", nearbyCountry = "Indonesia", region = "Pacific Ocean"},
        {sea = "Banda Sea", nearbyCountry = "Maluku Islands (Indonesia)", region = "Pacific Ocean"},
        {sea = "Arafura Sea", nearbyCountry = "Australia and Indonesia", region = "Pacific Ocean"},
        {sea = "Coral Sea", nearbyCountry = "Australia (Great Barrier Reef)", region = "Pacific Ocean"},
        {sea = "Tasman Sea", nearbyCountry = "New Zealand and Australia Coast", region = "Pacific Ocean"},
        {sea = "Bering Sea", nearbyCountry = "United States (Alaska) and Russia", region = "Pacific Ocean"},
        {sea = "Sea of Okhotsk", nearbyCountry = "Russia Coast", region = "Pacific Ocean"},
        {sea = "Hawaii Archipelago", nearbyCountry = "Hawaii Islands (USA)", region = "Pacific Ocean"},
        {sea = "Fiji Waters", nearbyCountry = "Fiji Islands", region = "Pacific Ocean"},
        {sea = "Bora Bora Coast", nearbyCountry = "French Polynesia", region = "Pacific Ocean"},
        {sea = "Tahiti Coast", nearbyCountry = "French Polynesia", region = "Pacific Ocean"},
        {sea = "Galapagos Waters", nearbyCountry = "Galapagos Islands (Ecuador)", region = "Pacific Ocean"},
        {sea = "Samoa Islands Coast", nearbyCountry = "Samoa", region = "Pacific Ocean"},
        {sea = "Mariana Trench", nearbyCountry = "Guam Island", region = "Pacific Ocean"},
        {sea = "Papua New Guinea Coast", nearbyCountry = "Papua New Guinea", region = "Pacific Ocean"},
        {sea = "Solomon Sea", nearbyCountry = "Solomon Islands", region = "Pacific Ocean"},
        {sea = "Gulf of California", nearbyCountry = "Mexico Coast", region = "Pacific Ocean"},
        {sea = "Gulf of Alaska", nearbyCountry = "USA Coast", region = "Pacific Ocean"}
    },
    [5] = { -- INLAND SEAS & LARGE BASINS
        {sea = "Caspian Sea", nearbyCountry = "Azerbaijan and Iran Coast", region = "Inland Sea"},
        {sea = "Caspian Sea", nearbyCountry = "Kazakhstan, Turkmenistan, Russia", region = "Inland Sea"},
        {sea = "Black Sea", nearbyCountry = "Turkey, Georgia, Bulgaria Coast", region = "Inland Sea"},
        {sea = "Sea of Azov", nearbyCountry = "Ukraine and Russia", region = "Inland Sea"},
        {sea = "Mediterranean Sea", nearbyCountry = "Italy, Greece, Egypt", region = "Inland Sea"},
        {sea = "Tyrrhenian Sea", nearbyCountry = "Italy (Sicily and Sardinia)", region = "Inland Sea"},
        {sea = "Adriatic Sea", nearbyCountry = "Italy and Croatia", region = "Inland Sea"},
        {sea = "Aegean Sea", nearbyCountry = "Greece and Turkey", region = "Inland Sea"},
        {sea = "Ionian Sea", nearbyCountry = "Greece and Italy", region = "Inland Sea"},
        {sea = "Baltic Sea", nearbyCountry = "Sweden, Finland, Poland", region = "Inland Sea"},
        {sea = "Gulf of Bothnia", nearbyCountry = "Sweden and Finland", region = "Inland Sea"},
        {sea = "Suez Canal", nearbyCountry = "Egypt", region = "Inland Sea"},
        {sea = "Panama Canal", nearbyCountry = "Panama", region = "Inland Sea"},
        {sea = "Lake Superior", nearbyCountry = "United States and Canada Coast", region = "Great Lakes Basin"},
        {sea = "Lake Victoria", nearbyCountry = "Tanzania and Uganda", region = "Inland Sea"},
        {sea = "Lake Baikal", nearbyCountry = "Russia", region = "Inland Sea"},
        {sea = "Lake Tanganyika", nearbyCountry = "Tanzania and DRC", region = "Inland Sea"}
    }
}

return locationDB
